apiVersion: v1
entries:
  nrc:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-12-31T14:12:33.904745Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 13dfa94959c71982eb297fa27de4b227bfc2e62376fca081bee297482878ad85
    home: nrc.zaakonline.nl
    icon: nrc.zaakonline.nl
    name: nrc
    urls:
    - nrc-0.1.0.tgz
    version: 0.1.0
  postgresql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 11.10.0
    created: "2020-12-31T14:12:33.9168825Z"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: Chart for PostgreSQL, an object-relational database management system
      (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: eebe8f456cf98d5927a35666d1d899174dc4d3e09f26788033f761527bc90749
    home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    - https://www.postgresql.org/
    urls:
    - charts/postgresql-10.1.1.tgz
    version: 10.1.1
  rabbitmq:
  - annotations:
      category: Infrastructure
    apiVersion: v2
    appVersion: 3.8.9
    created: "2020-12-31T14:12:33.9296197Z"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: Open source message broker software that implements the Advanced
      Message Queuing Protocol (AMQP)
    digest: 9e1aa941274a5bd3dced7ba120ffdf308ab7db7271f40603e4a134e74e9adba0
    home: https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq
    icon: https://bitnami.com/assets/stacks/rabbitmq/img/rabbitmq-stack-220x234.png
    keywords:
    - rabbitmq
    - message queue
    - AMQP
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: rabbitmq
    sources:
    - https://github.com/bitnami/bitnami-docker-rabbitmq
    - https://www.rabbitmq.com
    urls:
    - charts/rabbitmq-8.6.1.tgz
    version: 8.6.1
generated: "2020-12-31T14:12:33.8855429Z"
