apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-worker
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-worker
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-worker
        app.kubernetes.io/part-of: {{ .Release.Name }}
        helm.sh/chart: {{ include "chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ .Release.Name }}-php
          image: "{{ .Values.php.image }}:{{ .Values.php.tag }}"
          imagePullPolicy: {{ .Values.php.pullPolicy }}
          args:
              - bin/console
              - messenger:consume
              - async
              - -vv
          env:
              - name: JWT_SECRET_KEY
                value: '%kernel.project_dir%/config/jwt/private.pem'
              - name: JWT_PUBLIC_KEY
                value: '%kernel.project_dir%/config/jwt/public.pem'
              - name: JWT_PASSPHRASE
                value: 'bafe1dc254b45471754c221081f874aa'
              - name: APP_ENV
                value: 'prod'
              - name: TRUSTED_HOSTS
                valueFrom:
                    configMapKeyRef:
                        name: {{ template "fullname" . }}
                        key: trusted-hosts
              - name: TRUSTED_PROXIES
                valueFrom:
                    configMapKeyRef:
                        name: {{ template "fullname" . }}
                        key: trusted-proxies
              - name: APP_VERSION
                valueFrom:
                    configMapKeyRef:
                        name: {{ template "fullname" . }}
                        key: app-version
              - name: APP_DEBUG
                valueFrom:
                    configMapKeyRef:
                        name: {{ template "fullname" . }}
                        key: debug
              - name: APP_CACHE
                valueFrom:
                    configMapKeyRef:
                        name: {{ template "fullname" . }}
                        key: cache
              - name: DATABASE_URL
                valueFrom:
                    secretKeyRef:
                        name: {{ template "fullname" . }}
                        key: database-url
              - name: CORS_ALLOW_ORIGIN
                valueFrom:
                    configMapKeyRef:
                        name: {{ template "fullname" . }}
                        key: app-corsAllowOrigin
              - name: APP_APPLICATION_KEY
                valueFrom:
                    secretKeyRef:
                        name: {{ template "fullname" . }}
                        key: app_application_key
            {{ if .Values.redis.enabled }}
              - name: REDIS_HOST
                valueFrom:
                    configMapKeyRef:
                        name: {{ template "fullname" . }}
                        key: redis-host
              - name: REDIS_PORT
                valueFrom:
                    configMapKeyRef:
                        name: {{ template "fullname" . }}
                        key: redis-port
                          {{- end }}
    
                        #RabbitMQ
              - name: RABBITMQ_HOST
                valueFrom:
                    configMapKeyRef:
                        name: {{ template "fullname" . }}
                        key: rabbitmq-host
              - name: RABBITMQ_PORT
                valueFrom:
                    configMapKeyRef:
                        name: {{ template "fullname" . }}
                        key: rabbitmq-port
              - name: RABBITMQ_USERNAME
                valueFrom:
                    secretKeyRef:
                        name: {{ template "fullname" . }}
                        key: rabbitmq-username
              - name: RABBITMQ_PASSWORD
                valueFrom:
                    secretKeyRef:
                        name: {{ template "fullname" . }}
                        key: rabbitmq-password
    
              - name: APP_URL
                value: https://{{ $.Values.ingress.domain }}/{{ $.Values.ingress.path }}
              
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
